#
# config/make/linux-common.mk
#

ifeq ($(TARGET_ARCHITECTURE), x86)
	INTERNAL_TARGET_ARCHITECTURE = -m32
else ifeq ($(TARGET_ARCHITECTURE), x64)
	INTERNAL_TARGET_ARCHITECTURE = -m64
else
$(error The target architecture is invalid ($(TARGET_ARCHITECTURE)).)
endif

ifndef TARGET_NAME
$(error The target name is not defined.)
endif


# Default build directories

ifndef BUILD_OUTPUT_DIRECTORY
	BUILD_OUTPUT_DIRECTORY = ../build/$(TARGET_PLATFORM)/$(TARGET_ARCHITECTURE)/$(TARGET_CONFIGURATION)
endif

ifndef BUILD_INTERMEDIATE_DIRECTORY
	BUILD_INTERMEDIATE_DIRECTORY = $(BUILD_OUTPUT_DIRECTORY)/obj/$(TARGET_NAME)
endif


# Default compiler settings

COMPILER_C_FLAGS   += $(INTERNAL_TARGET_ARCHITECTURE)
COMPILER_C++_FLAGS += $(INTERNAL_TARGET_ARCHITECTURE)


# Default archiver settings

ARCHIVER	   += ar
ARCHIVER_FLAGS += -crs


# Default linker settings

COMPILER_C_LINKER_FLAGS			 += $(INTERNAL_TARGET_ARCHITECTURE) -L$(BUILD_OUTPUT_DIRECTORY)
COMPILER_C_LINKER_SHARED_FLAGS	 += -fPIC -shared
COMPILER_C++_LINKER_FLAGS		 += $(INTERNAL_TARGET_ARCHITECTURE) -L$(BUILD_OUTPUT_DIRECTORY)
COMPILER_C++_LINKER_SHARED_FLAGS += -fPIC -shared
